### PR TITLE
Enhance fcdr uncertainty information

### PR DESCRIPTION
**Pull request by gerritholl**
Add implementations for calculation of correlation scales according to CM recipes document.

I still intend to push some more commits to this as it's not final yet.

But the answer is 4.04646028!  :dolphin:

Still same :bug: around for sure.

### CODE REVIEW

**Comment by patternizer** [comment]
Well done. I am in awe that it works - brilliant! Of course, you do know that the answer should be the integer 42 and not 4.04646028. Anyway, I'm checking the logic and so far, I don't see anything wrong so I guess Douglas Adams got his answer wrong.

**Comment by gerritholl** [comment]
Or I still have some bugs to fix :)

**Comment by gerritholl** [comment]
4 makes theoretical sense.  I recalibrate every 40 scanlines.  I skip 4 out of 5 lines for memory reasons.  So the number 4 actually means 20 lines, which is the average number for which `r(n_l, n_l')=1`.

**Comment by patternizer** [comment]
I expect that the smoothing scale should be a baseline - that's great. Terms correlated on longer timescales should hopefully reveal their correlation scales driven by the underlying physics and be in excess of this.

**Pull request merged**
