### PR TITLE
Fix bug in satellite angle calculation

### LINKED ISSUE #304: Satellite azimuth angles may be losing precision when ill-conditioned, and should be restricted to [-180, 180]
@cbulgin reports that satellite azimuth angles at times look strange:

image

Certainly, they should be restricted to [-180, 180] like solar azimuth angles.  But there are also some other discontinuities that may not correspond to what one would expect, should investigate.

### PR DESCRIPTION
**Pull request by gerritholl**
The satellite angle calculation was performed assuming a satellite
position above position 28 rather than between 28 and 29.  Also, my
calculation of crossing the meridian did not make sense, this needs to be
per scanline.

This should fix #304 as reported by @cbulgin

### CODE REVIEW

**Comment by gerritholl** [comment]
This is what the corrected image looks like:

image

**Comment by gerritholl** [comment]
Or rather (improved colormap):

image

**Comment by cbulgin** [comment]
Yes, I think this looks better.  Are you going to report azimuth angles in the range -180 to 180 rather than 0-360?


Dr C E Bulgin

skype: cbulgin
tel: 0118 378 7717

Room 3L71 
Department of Meteorology
University of Reading
3 Earley Gate, PO Box 238
Whiteknights Campus
Reading, RG6 6AL

**Comment by gerritholl** [comment]
I'm not sure.  I don't think we have defined in the project whether we have azimuth angles in [-180, 180] or in [0, 360], but we probably should.  I'll send a mail around.

**Pull request merged**
